### ISSUE TITLE
Some text still hard to see

### ISSUE THREAD

**Issue by basnijholt** [naofireblade/clear-theme-dark#1]
Hi, first of all, thanks a lot for making this!

Some text, like "Help translating" (see below) is still hard to see.

![image](https://user-images.githubusercontent.com/6897215/69014728-b29e9f00-098d-11ea-92e7-d5947694e2f7.png)

Maybe another color would be good?

**Comment by aptonline** [comment]
Yep I’m seeing the same thing when looking at entities.

![DF3950E8-496C-419B-A0F5-7223A3B1600E](https://user-images.githubusercontent.com/190136/72921342-ff627580-3d42-11ea-9864-39d730901314.jpeg)

**Comment by aptonline** [comment]
I believe this is the `primary-color` css and is set dark so that the iOS app header matches the HA top bar.  There is an issue open for the iOS app to hopefully resolve this: https://github.com/home-assistant/home-assistant-iOS/issues/531

**Comment by naofireblade** [comment]
Until HA 0.103 it was not possible to color the navigation header dark. I updated the theme to support this now.
The issue with the iOS app remains but a fix of the app is already in the pipeline.
