### ISSUE TITLE
Recorder component throwing errors...

### ISSUE THREAD

**Issue by ronsum232** [naofireblade/clear-theme-dark#3]
Log Details (ERROR)

Error saving event: <Event themes_updated[L]: themes=clear-dark=lovelace-background=center / cover no-repeat url(data:image/jpeg;base64,/9j/4AAQSkZJRgABAQEAYABgAAD/[...]'), primary-color=rgba(255, 159, 9, 1), light-primary-color=[...]
MySQLdb._exceptions.DataError: (1406, "Data too long for column 'event_data' at row 1")

The above exception was the direct cause of the following exception:
[...]
sqlalchemy.exc.DataError: (MySQLdb._exceptions.DataError) (1406, "Data too long for column 'event_data' at row 1")
[SQL: INSERT INTO events (event_type, event_data, origin, time_fired, created, context_id, context_user_id) VALUES (%s, %s, %s, %s, %s, %s, %s)]
[...]
(Background on this error at: http://sqlalche.me/e/9h9h)

**Comment by naofireblade** [comment]
Hi this occurs because of the embedded background image.

To circumvent this problem you need to download the background image and reference it in the yaml. I added instructions how to do that: https://github.com/naofireblade/clear-theme-dark#known-problems
