### ISSUE TITLE
Illegible button text in HACS restart dialog

### ISSUE THREAD

**Issue by hjdarnel** [naofireblade/clear-theme-dark#4]
Hopefully these images show enough. When I update a HACS package and it prompts me to restart, the text is illegible. 
![chrome_2020-02-28_15-48-06](https://user-images.githubusercontent.com/7868899/75590049-0ebf9780-5a42-11ea-945d-59fb40e84fdf.png)
![chrome_2020-02-28_15-48-01](https://user-images.githubusercontent.com/7868899/75590050-0f582e00-5a42-11ea-967c-75019d40a006.png)

related to #1

**Comment by naofireblade** [comment]
This was fixed in HACS 0.22.0
