### ISSUE TITLE
Safemode was activated after updating via HACS

### ISSUE THREAD

**Issue by sgtsilver** [naofireblade/clear-theme-dark#9]
Error Message as follows:

2021-02-07 12:08:19 ERROR (SyncWorker_3) [homeassistant.util.yaml.loader] while parsing a block mapping
in "/config/themes/clear-dark-vibrant/clear-dark-vibrant.yaml", line 5, column 3
expected , but found ''
in "/config/themes/clear-dark-vibrant/clear-dark-vibrant.yaml", line 39, column 33

**Comment by naofireblade** [comment]
Hi clear dark **vibrant** is another theme. Not mine :)
